name: Auto Tag on Commit

on:
  push:
    branches:
      - QA

jobs:
  auto-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "20-VIGNESH-K"
          git config user.email "vigneshvignesh7035@gmail.com"

      - name: Get previous tag
        id: get_previous_tag
        run: |
          git fetch --prune --unshallow
          previous_tag=$(git describe --tags --abbrev=0)
          echo "Previous tag: $previous_tag"
          echo "::set-output name=previous_tag::$previous_tag"

      - name: Bump version
        id: bump_version
        run: |
          # Extract the previous tag
          previous_tag="${{ steps.get_previous_tag.outputs.previous_tag }}"
          
          # Extract the version number
          IFS='.' read -r major minor patch <<< "$previous_tag"
          
          # Increment the patch version
          patch=$((patch + 1))
          new_version="${major}.${minor}.${patch}"
          
          echo "New Version = $new_version"
          echo "::set-output name=new_version::$new_version"

      - name: Tag and push changes
        if: github.ref == 'refs/heads/QA'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          new_tag="v${{ steps.bump_version.outputs.new_version }}"
          git tag "$new_tag"
          git push origin "$new_tag"
