name: Create Tag on Commit in QA Branch

on:
  push:
    branches:
      - 'QA-*'

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "20-VIGNESH-K"
          git config --global user.email "vigneshvignesh7035@gmail.com"

      - name: Get current branch name
        id: branch_name
        run: echo "::set-output name=branch::$(git symbolic-ref --short HEAD)"

      - name: Get latest tag for the branch
        id: latest_tag
        run: |
          latest_tag=$(git describe --tags --match "v1.0.*_${{ steps.branch_name.outputs.branch }}*" --abbrev=0 || echo "v1.0.0_${{ steps.branch_name.outputs.branch }}")
          echo "::set-output name=tag::${latest_tag}"

      - name: Determine new tag number
        id: new_tag_number
        run: |
          current_tag_number=$(echo "${{ steps.latest_tag.outputs.tag }}" | cut -d'.' -f3 | cut -d'_' -f1)
          new_tag_number=$((current_tag_number + 1))
          echo "::set-output name=new_tag::${new_tag_number}"

      - name: Create and push new tag
        run: |
          git tag "v1.0.${{ steps.new_tag_number.outputs.new_tag }}_${{ steps.branch_name.outputs.branch }}"
          git push origin "v1.0.${{ steps.new_tag_number.outputs.new_tag }}_${{ steps.branch_name.outputs.branch }}"
